asd

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -27,9 +27,10 @@ jobs:
           python -m playwright install --with-deps
 
       - name: Run Tests
+        id: run_tests
         run: |
           pytest ${{ matrix.test_path }} --browser ${{ matrix.browser }} --tracing=retain-on-failure
-        continue-on-error: true
+          echo $? > test-exit-code.txt
 
       - name: Upload Playwright Traces
         uses: actions/upload-artifact@v4
@@ -37,6 +38,14 @@ jobs:
         with:
           name: playwright-traces
           path: test-results/
+
+      - name: Fail if Tests Failed
+        run: |
+          code=$(cat test-exit-code.txt)
+          if [ "$code" -ne 0 ]; then
+            echo "❌ Tests failed with exit code $code"
+            exit $code
+          fi
 
   test-visual:
     runs-on: ubuntu-latest
@@ -69,7 +78,7 @@ jobs:
       - name: Run Tests
         run: |
           pytest ${{ matrix.test_path }} --browser ${{ matrix.browser }} --tracing=retain-on-failure
-        continue-on-error: true
+          echo $? > test-exit-code-visual.txt
 
       - name: Compare Snapshot State
         id: check_snapshots
@@ -94,3 +103,11 @@ jobs:
         with:
           name: playwright-traces-${{ matrix.browser }}-tests_visual
           path: test-results/
+
+      - name: Fail if Tests Failed
+        run: |
+          code=$(cat test-exit-code-visual.txt)
+          if [ "$code" -ne 0 ]; then
+            echo "❌ Tests failed with exit code $code"
+            exit $code
+          fi
